enum
{
    IDLE_STATE,
    STEP_INIT_STATE,
    SECOND_STATE, //TODO:
    MATERIAL_CONTROL_STATE,
    STEP_POSITION_STATE,
    STEP_HOME_SWITCH_CONTROL,
    STEP_LAST_STATE,
    MAINTENANCE_STATE
} Alstate;